### ISSUE TITLE
Hellfest

### ISSUE THREAD

**Issue by Peter-87** [davisnando/ticketswap_bot#5]

**Comment by killer4nl** [comment]
> _No description provided._

Pm me

**Comment by slidinglight** [comment]
> > _No description provided._
> 
> Pm me

Sent you a friend request on discord.

**Comment by Just08** [comment]
Hi,
is it possible to use this to get HF 2022 ticket ? If yes can you explain me how to use your script please ? 
Thanks

**Comment by davisnando** [comment]
I've updated the whole bot so that it works agains. See the readme how to get it
