### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by REDitor** [davisnando/ticketswap_bot#6]
Hi,

I was wondering if this still works, and if so, how to use it?

**Comment by baksteen123** [comment]
hi,

did you figure it out?

greatings

**Comment by REDitor** [comment]
No sadly not, I’m clueless about python

**Comment by baksteen123** [comment]
me neither, but i do know some people who do. ill let you know if i made it work :)

**Comment by KhaledZidane** [comment]
Hello, Anyone found a way?!

**Comment by ulasdinc** [comment]
Hello, I am also interested in this but could not make it work :/

**Comment by Mgxcx** [comment]
Did someone used that bot lately ? 

Tickets are sold so fast on TicketSwap even when you click right away on your notification, I can’t believe it’s a human behind !

**Comment by davisnando** [comment]
I've updated the whole bot so that it works agains. See the readme how to get it
